# Site
repository: NgaAdrain/NgaAdrain.github.io
favicon: image/green_taebo.jpg

# Content configuration version
version: 2

# Personal info
name: Adrain
title: Happy? Happy!? AI Developer
email: nugoonga@gmail.com
website: www.github.com/NgaAdrain

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Adrain_Producer
github_username:  NgaAdrain
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: Nga Adrain
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: image/green_bonobono.jpg
about_content: | # this will include new lines to allow paragraphs
  헛소리 하지마 임마 ww <br>
  [소스코드](github.com/ngaadrain/Adrain_Code_History/tree/master/School)
  - Python : 2015, 2019 ~ current
  - C : 2015,2018 ~ 2019(with Linux, Embedded)
  - C++ : 2016,2018 ~ current(Data Structure, File Structure,for Algorithm Implementation)
  - Java : 2018~2019(Web, Android)
  - Web(HTML,JavaScript,CSS,etc...) : 2019<br> (from Web Programming Course)
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Enter Text here
        link: github.com/NgaAdrain
        # link_text: Project Website
        additional_links:
          - title:  ngaadrain/team-enter-text-here
            icon: fab fa-github
            url: github.com/ngaadrain/team-enter-text-here
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is our Graduate Project
        description: | # this will include new lines to allow paragraphs
          Team: Enter Team Name here <br>
          Car Moving Recognition System With Sim2Real Deeplearning Based System For Behicle Status Analysis 
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Pusan National University
        caption: 2015 - 2021
        sub_title: BSc Computer Science
        quote: >
          부산에 위치한 4년제 국립 대학교. 
        description: | # this will include new lines to allow paragraphs
          [부산대](https://www.pusan.ac.kr/kor/Main.do) 전기컴퓨터공학부 정보컴퓨터공학전공 공학사.

  - title: 본인
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 개발자 지망
      - [AI 공부중](https://github.com/NgaAdrain/Adrain_Code_History/tree/master/Busan_AI_Class)
      - DNN, CNN을 조금 써봄
      - PyTorch는 좀 어렵다고 느껴짐.
      - Keras 짱짱
      - 아 [코로나](https://www.kaggle.com/andyczhao/covidx-cxr2) 가 [꼴받게 하자너어어](https://nbviewer.jupyter.org/github/NgaAdrain/Adrain_Code_History/blob/master/Busan_AI_Class/COVID/COVID_XRAY_Classification_sep_complete.ipynb)
      - 완벽한 정답은 없지만 완벽한 오답은 있다.
      - 다름은 틀림이 아니다.
      - 그리고 난 이상한 사람이다(?)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
